### ISSUE TITLE
Hang after creating new session with "already running with pid ..." message

### ISSUE THREAD

**Issue by colin-m-fletcher** [stargatedaw/stargate#16]
**Describe the bug**
After starting stargate and choosing "New", a dialogue appears in front of the splash screen claiming: "Detected: Stargate is already running with pid ...". There is only one instance running: the one that's just been started, but at this point, it's hung. "OK" in the dialogue does nothing. The project directory has been created, but it is empty.

This occurs with current git main branch: I don't know whether it has ever worked in the past.

**To Reproduce**
In the Stargate source directory, run `scripts/stargate`, and click the "New" button.

**Expected behavior**
A new session should be rreated.

**Screenshots**
![image](https://user-images.githubusercontent.com/3357212/140057327-bb4ba194-23d0-4e47-aed2-79d45f4a9aa5.png)

**Hardware and operating system**
CPU: Intel Core i9
Memory: 16GB 
Form factor: laptop
CPU arch: x86_64
debian "bullseye", kernel 5.10.0-9-amd64, xfce 4.16

**Comment by ghost** [comment]
Thanks for reporting.  Can you please send me your `~/stargate/config/device.txt`,  `~/stargate/log/*` file(s) (either attach here, or send them privately in our Discord server), and the output of these commands when this is happening but Stargate DAW is not running:
```
pgrep stargate
pgrep stargate-engine
# Or whatever pid the messagebox is currently showing
ps -ef | grep 166516
```

**Comment by colin-m-fletcher** [comment]
Here's the log file from my last failed attempt:
[stargate.log](https://github.com/stargateaudio/stargate/files/7470304/stargate.log)

`~/stargate/config/device.txt` doesn't exist here.

`pgrep` doesn't find any stargate processes while it's hung with the dialogue showing:
```
colinf@colinf-xps15:~$ pgrep stargate
colinf@colinf-xps15:~$ pgrep stargate-engine
colinf@colinf-xps15:~$ ps -ef | grep 182517
colinf    182517    8184  0 19:55 pts/14   00:00:00 python3 scripts/stargate
```

**Comment by colin-m-fletcher** [comment]
Ah, sorry for the noise: realised I was still missing some python dependencies.

Running `pip3 install -r requirements.txt` told me `Installing collected packages: wavefile, pymarshal, mido`, and now things get a bit further.

**Comment by ghost** [comment]
All good.  BTW, there is [this document](https://github.com/stargateaudio/stargate/blob/main/docs/building.md) for help building.  Also separate docs for Windows, ARM and Mac.
