### ISSUE TITLE
Both the deb files have dependency issues

### ISSUE THREAD

**Issue by CHJ85** [stargatedaw/stargate#25]
Hi there. I'm using Pop OS which is base on Ubuntu 20.04. But for whatever reason, there are dependency issues.
Could you please look into this? And if it's not fixable, could you please put out a flatpak?
That might actually be a better solution than having to package rpm and deb files each time there's a new release.
And btw. Please provide better documentation for source compiling.
I tried compiling from source, but there's no cmake, and using "make" gave me "error 2".

EDIT: The problem dependencies seem to be fftw3, python3-pyqt6.qtsvg, python3-pyqt6. None of them exist.

**Comment by ghost** [comment]
I'm guessing you tried to download and install using `dpkg`?  `dpkg` does not install dependencies, so they would all be missing, always.  I downloaded the latest Stargate DAW into a POP OS 20.04 live image in a VM, double clicked on the installer, clicked the `Install` button, and it worked.  Alternately, `sudo apt install ./stargate-*.deb` would also install the dependencies.

**Comment by ghost** [comment]
Also, I am trying to package Stargate DAW into a universal Linux package.  At the moment, the top 2 contenders are AppImage or a Pyinstaller portable executable.  But there are challenges to using any of these packaging formats for something as complex as a DAW.

**Comment by CHJ85** [comment]
Thank you so much. That worked. See. I installed it using qapt deb installer because I removed the Pop Shop. Not sure why dpkg ignores dependencies.
Sorry for the trouble.

**Comment by ghost** [comment]
All good
