### ISSUE TITLE
Strange saving of recorded samples (Win10)

### ISSUE THREAD

**Issue by DreadDendy** [stargatedaw/stargate#27]
Hello, I decided to try and test this new DAW (on Win10 currently).

First I have tried sample recording. It is actually worked, but it saved sample (from microphone) in a bit strange way. The file actually appeared in two locations.

First one in the audio/rec in project's directory,
C:\Users\DreadDendy\stargate\projects\testProject\audio\rec\test_sample-1-1.wav

The path to the second one is really weird. Seems like it once again used path to project's directory,
C:\Users\DreadDendy\stargate\projects\testProject\audio\samples\C\Users\DreadDendy\stargate\projects\testProject\audio\rec\test_sample-1-1.wav

**Comment by ghost** [comment]
Hello @DreadDendy .

Thanks for reporting.  This should have been fixed in the latest release 4 days ago (21.12.2).  I did a quick test and confirmed that a recorded audio file was not duplicated.  Please let me know if you continue to see this issue.

**Comment by DreadDendy** [comment]
I already got latest version (21.12.2) and it definetely happening each time I recording audio. Will it help if I attach log file? I deleted old one and then launched DAW, then done record, then exit, so it is compact.
[stargate.log](https://github.com/stargateaudio/stargate/files/7730405/stargate.log)

I think that couple of lines look interesting, especially the second one.
`[2021-12-17 00:00:01,554] INFO sglib\lib\process.py          : 62 - C:\Program Files\stargateaudio@github\Stargate\program\engine\stargate-engine.exe: "v_sg_configure:  key: "wp", value: "3|0.0|~/stargate/projects/testProject/audio/rec/test4-1-1.wav""`
`[2021-12-17 00:00:01,554] INFO sglib\lib\process.py          : 62 - C:\Program Files\stargateaudio@github\Stargate\program\engine\stargate-engine.exe: "v_audio_pool_add_item:  '~/stargate/projects/testProject/audio/samples' 'C/Users/DreadDendy/stargate/projects/testProject/audio/rec/test4-1-1.wav'"`

**Comment by ghost** [comment]
Oh, I know what it is.  I'll get it fixed tonight after work and into the next release.  Thanks!

**Comment by ghost** [comment]
It's fixed.  I will probably do another release later in the weekend.
