### ISSUE TITLE
Strange behaviour of save/discard when recording audio (Win10)

### ISSUE THREAD

**Issue by DreadDendy** [stargatedaw/stargate#29]
Hello, I have found something strange.
When first one recording discarded and second one saved then actually saved the first one.

My example is for using a microphone, but with the instruments there will be no differences.
Steps to reproduce:
1. Start recording audio, say something to the microphone
2. Stop recording and discard saving
3. Start recording audio again, say somehing different to the microphone
4. Stop recording and save sample
5. Check the sample and see that it is actually the sample from step 1

Here is the log file.
[stargate.log](https://github.com/stargateaudio/stargate/files/7776752/stargate.log)

**Comment by ghost** [comment]
Thanks for reporting.  I'm traveling right now, I'll fix this when i return in a few days

**Comment by ghost** [comment]
Confirmed that is only happens on Windows.  Seems to be a bug in libsndfile.  So I cleaned up how recorded audio files are handled to make it safer and more robust, and that seemed to fix the bug.  The fix will be in the next release  sometime soon.

As always, thanks for reporting!
