### ISSUE TITLE
stargate is in the AUR

### ISSUE THREAD

**Issue by kiasoc5** [stargatedaw/stargate#30]
Hi, I maintain stargate on the Arch User Repository. Perhaps you can put a link to the pkgbuild in the docs.

https://aur.archlinux.org/packages/stargate/

**Comment by ghost** [comment]
Thanks, I was hoping somebody would do this.  I added it to the `releases` page.

The PKGBUILD looks pretty good, a couple of comments:
- I believe Cython is not needed anymore
- If Qt6 is available in Arch, it should be preferred over Qt5, as it performs much better, especially on ARM.  Also, qt6-svg is required

**Comment by ghost** [comment]
All of the Arch Linux documentation is updated
