### ISSUE TITLE
Contact information?

### ISSUE THREAD

**Issue by BillyDM** [stargatedaw/stargate#33]
Hello! I'm interested in this project and would like to talk with you. I'm the lead developer of the (still WIP) [Meadowlark](https://github.com/MeadowlarkDAW/Meadowlark) DAW project.

While I think our projects ultimately have different design goals, I would still like to discuss if it makes sense to share some things between our projects. Namely things like DSP, sample libraries, or even plugin hosting? I know a lot about hosting [CLAP](https://github.com/free-audio/clap) plugins, and creating a simple CLAP host in C shouldn't be too hard (considering CLAP is a header-only C library).

I don't see any kind of contact information or chatroom linked anywhere. Is there a place we can discuss this more? If you just want to chat on the GitHub issues page, that's fine too.

**Comment by L3337** [comment]
Hi @BillyDM , nice to meet you, I am familiar with Meadowlark, been following it's progress for a while.

> DSP

As long as you license all of it GPL3, of course you can share it.  I'm not sure how that is meant to work, if you are planning to re-use it as C code, or porting it to Rust, or something else.  It's worth noting that while the DSP code is generally fast, efficient, stable and has good sound, I am planning "DSP 2.0" with Stargate DAW v2, primarily to solve some issues around certain suboptimal APIs, and some issues that cause certain plugins not to sound good at higher sample rates (especially, but not limited to FM1).  I wrote a lot of 10+ years ago, it could use a refresh, and maybe even consider increasing the CPU budget where it makes sense.

> sample libraries

You are 100% welcome to use this any way you see fit:  https://github.com/stargatedaw/stargate-sample-pack
I only request that you retain the notes put in there by the original authors who contributed the sample content.  I'm happy to collaborate on that further, I would love to see expanded high quality Creative Commons Zero sample libraries available to the masses.

> or even plugin hosting? I know a lot about hosting [CLAP](https://github.com/free-audio/clap) plugins, and creating a simple CLAP host in C shouldn't be too hard (considering CLAP is a header-only C library).

I've been considering this lately, offering support for CLAP.  VST3 is a hard sell for me, it is crazy complicated and will force a lot of VST3-isms and C++-isms into my DAW, but CLAP seems like a more logical choice.  But I might also decide to fork Stargate DAW into a new DAW with plugin support (CLAPGate? StarCLAP?), as I do rather like the old-school Propellerheads(tm) Reason(tm) experience where everything is rock-solid-stable and there is no need to manage dozens of plugins.  If the CLAP hosting version takes off in a major way, the non-plugin version could get deprecated, or vice-versa.  But that probably needs more research and design before any decision is made.

> I don't see any kind of contact information or chatroom linked anywhere. Is there a place we can discuss this more?

I'll send you an email tonight, from there we can potentially move the conversation to a mutually agreed upon chat app

> If you just want to chat on the GitHub issues page, that's fine too.

That also works
