### ISSUE TITLE
Doesn't build on artix ( arch ) linux

### ISSUE THREAD

**Issue by yust1n** [stargatedaw/stargate#37]
stargate/src/stargate-release-23.05.1/scripts$ python pkgbuild.py

==> Starting package()...
make: *** No rule to make target 'install_distro'.  Stop.
==> ERROR: A failure occurred in package().
    Aborting...
Traceback (most recent call last):
  File "/mnt/linux/aur/stargate/src/stargate-release-23.05.1/scripts/pkgbuild.py", line 117, in <module>
    assert not os.system('makepkg -fs')
AssertionError

Seems that the Makefile got changed. There's in no install_distro.

**Comment by yust1n** [comment]
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stargate
did it my way ... seems to works now

**Comment by L3337** [comment]
Hi @yust1n ,

I actually made a bunch of changes to how it installs now, thanks for reminding me that I forgot to update the `pkgbuild.py` script.  The new way that I'm packaging everything is to install everything in a single folder in `/opt/stargate` using `make install_self_contained`, and then symlink in /usr/share files like desktop files, icons, `/usr/bin/stargate`, etc...  using `make install_symlinks`.  Which ultimately simplifies the installation and allows switching between multiple installations just by calling them directly or changing the system symlinks (not that there is really a reason to have mutiple versions installed though).

Thanks for updating AUR.  It looks good, only concern is that you are deleting Soundtouch?  I'm assuming that will break time stretching for audio items, but maybe I'm misunderstanding what is happening in your PKGBUILD.  Also, unless I'm misunderstanding something again, it looks like you are not adding the symlinks to the desktop files, /usr/bin/stargate, etc... so it would have to be invoked with `/opt/stargate/scripts/stargate`?  I guess this line is removing the symlinks:
```
	sed "/\binstall_symlinks:/s/:.*/:/" -i Makefile 
```
, the question is:  What was happening that caused you to remove it?  Probably permissions issues?

After looking at, I think I need to replace things like:
```
    ln -s /opt/stargate/scripts/stargate \                                         
        $(DESTDIR)$(PREFIX)/bin/stargate || true 
```
with
```
    ln -rs $(DESTDIR)/opt/stargate/scripts/stargate \                                         
        $(DESTDIR)$(PREFIX)/bin/stargate || true 
```
But I will wait for your feedback before I make any changes.

**Comment by L3337** [comment]
I found a number of issues in the build system, so I went ahead and committed 5bb7f87.  That will probably solve all of your problems, and allow you to just do a simple `make install` without the extra hackery around it.  I'm not sure if Arch/AUR and their derivatives have Soundtouch in their repos (or if Stargate will be able to find the system version), but please do test time stretching audio with the default Soundtouch algorithm and  let me know.

**Comment by yust1n** [comment]
Don't worry ... all is fine !!!!
Just checked and icons are there ... didn't think of that because i do all the stuff in the shell.
The sed just removes the call in the Makefile to remove the symlinks ... breaks the build since there are no symlinks to delete.
damn ... lol .... crosspost .... 
There is no issue anymore with my PKGBUILD but now there might be new ones :D
rm -rf src/vendor/soundtouch/ and  rm -rf src/vendor/portaudio-binaries/ just delete empty dirs so git submodule works proper.
Anyways I am damn tired .... will have a look at what you did tomorrow.

**Comment by L3337** [comment]
>  there is no issue anymore with my PKGBUILD but now there might be new ones :D

Yeah, the life of a package maintainer, I maintain some packages also :-D

Let me know if you run into any problems.  I have no plans of making more changes to the build system (unless you report any other issues I need to fix), so it should be stable after this.

**Comment by L3337** [comment]
Also, these lines should be able to go away:
```
	mkdir -p ${pkgdir}/usr/bin
	mkdir -p ${pkgdir}/usr/share/{doc,applications,pixmaps}
	mkdir -p ${pkgdir}/usr/share/mime/packages
```
That was another bug that I fixed.

EDIT:  If using the default symlinking mechanism in the stock `Makefile`

**Comment by L3337** [comment]
Fixed pkgbuild.py as well.  Couldn't run Stargate on my Manjaro VM because they broke the PyQt6 package by pairing it with an older version of Qt6, but everything appeared to install correctly.  This is my `PKGBUILD` with the new fixes:
https://github.com/stargatedaw/stargate/blob/main/scripts/pkgbuild.py#L70-L83

**Comment by yust1n** [comment]
Nice :)
Since this PKGBUILD is based on releases i will take care when 23.05.02 will be out.
Thanks !

**Comment by L3337** [comment]
I'm in the middle of releasing right now.  Thanks for the bug report and AUR packaging, not sure how I missed all of these issues, but glad to have them fixed.

**Comment by yust1n** [comment]
Thanks 23.05.2 i found a real big bug in my PKGBUILD !!!
I will update it tomorrow ... already did some tests and i feel really stupid now :D
Time to play with the new release .... I need to find out how to loop audio and stuff.

**Comment by L3337** [comment]
> I will update it tomorrow ...

Awesome, I appreciate it :-)  The AUR package went unmaintained for quite a while when an update to `pacman` broke it, grateful that you got it working again.

> I need to find out how to loop audio and stuff.

Just right-click on the sequencer timeline and set the region start and end.  Then click the loop button on the transport to toggle looping the region.

**Comment by yust1n** [comment]
Works now. I tested it with yay.
Finding out how to loop wasn't a big problem but playing with timestretch in the waveeditor gave me strange results.

**Comment by L3337** [comment]
>  but playing with timestretch in the waveeditor gave me strange results.

We basically just repackage all of the open source time stretching / pitch shifting libraries, with the exception of:

+ Time (Affecting Pitch)
+ Pitch (Affecting Time)

, which simply re-pitch the audio in real time.

The open source libraries have the following known issues:
+ Soundtouch:  Usually pretty accurate on time, but sometimes the pitch is not what it was supposed to be, depending on the content.  Also, sometimes it massively distorts the audio, usually Rubberband is a better choice when this happens
+ Rubberband:  Generally sounds pretty good and is accurate on pitch, but often the accuracy of the length isn't 100%
+ Paulstretch: Not accurate on time, meant for turning sounds into atmospheres by stretching/smearing them very much
+ SBMS: Sometimes sounds strange, fairly accurate on pitch, often not very accurate on time, only works on Linux and Mac x86, does not work on ARM or Windows, where the option for it is hidden

If you ran into something else, please let me know.  I'll create a separate issue for the time stretching known issues.

**Comment by yust1n** [comment]
I have to start stargate with LC_ALL=C otherwise I get

[2023-05-10 11:06:36,053] ERROR /opt/stargate/sglib/log.py    : 105 - Traceback (most recent call last):

  File "/opt/stargate/sgui/sgqt.py", line 411, in _editingFinished
    value = self._str_to_value(value)

  File "/opt/stargate/sgui/sgqt.py", line 258, in _str_to_value
    value = float(_str)

ValueError: could not convert string to float: '1,2E+01'

[2023-05-10 11:06:40,946] ERROR /opt/stargate/sglib/log.py    : 105 - Traceback (most recent call last):

  File "/opt/stargate/sgui/sgqt.py", line 411, in _editingFinished
    value = self._str_to_value(value)

  File "/opt/stargate/sgui/sgqt.py", line 258, in _str_to_value
    value = float(_str)

ValueError: could not convert string to float: '1,7E+02'

[2023-05-10 11:06:40,949] ERROR /opt/stargate/sglib/log.py    : 105 - Traceback (most recent call last):

  File "/opt/stargate/sgui/sgqt.py", line 272, in mousePressEvent
    self.value_at_press = self.value()

  File "/opt/stargate/sgui/sgqt.py", line 358, in value
    return float(text)

ValueError: could not convert string to float: '1,2E+01'

[2023-05-10 11:06:53,830] ERROR /opt/stargate/sglib/log.py    : 105 - Traceback (most recent call last):

  File "/opt/stargate/sgui/wave_edit/__init__.py", line 72, in ok_handler
    f_stretch = self.timestretch_amt.value()

  File "/opt/stargate/sgui/sgqt.py", line 358, in value
    return float(text)

ValueError: could not convert string to float: '1,2E+01'

Guess it's time to close this issue and move to a new one which is also kinda solved since it must be about localization.
