### ISSUE TITLE
Can't compile from source

### ISSUE THREAD

**Issue by windowsrefund** [stargatedaw/stargate#42]
~/src/stargate-release-23.12.1
> cd src

~/src/stargate-release-23.12.1/src
> make
make -C vendor/sbsms/cli
make[1]: *** vendor/sbsms/cli: No such file or directory.  Stop.
make: *** [Makefile:233: sbsms] Error 2

**Comment by L3337** [comment]
Hello.  You are missing the git submodules.  Either clone with:
```
git clone --recursive https://github.com/stargatedaw/stargate.git
```
or run
```
git submodule init
git submodule update
```
[Full Linux build instructions are here](https://github.com/stargatedaw/stargate/tree/main/src/linux).  The instructions may be a little outdated, let me know if you run into issues with them.
