### ISSUE TITLE
Unable to create new project in windows 11 latest

### ISSUE THREAD

**Issue by martjay** [stargatedaw/stargate#43]
**Describe the bug**
Unable to create new project in windows 11 latest

**To Reproduce**
Today is my first time installing this software, but when I opened the software to create a new project, there was no response. I don't know what the problem is.

**Hardware and operating system**
CPU: i7 10700K
Memory: 64 GB
Form factor: desktop
CPU arch: x64, AMD
Windows: version 11

**Additional context**

**Attach your log file**
[stargate.log](https://github.com/stargatedaw/stargate/files/14003756/stargate.log)

**Comment by L3337** [comment]
Hello @martjay .  Thanks for reporting this issue.  I see this in the attached log:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
```

What locale and language is your Windows 11 install?  I will create a VM of WIndows 11 in your locale and language to reproduce the problem.

**Comment by martjay** [comment]
> Hello @martjay . Thanks for reporting this issue. I see this in the attached log:
> 
> ```
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
> ```
> 
> What locale and language is your Windows 11 install? I will create a VM of WIndows 11 in your locale and language to reproduce the problem.

Chinese simple

**Comment by L3337** [comment]
Thanks @martjay .  I was not able to reproduce the problem in Windows 11 Chinese Simplified, but I think I understand what is happening.  Please try this build:
https://github.com/stargatedaw/stargate/releases/tag/release-24.02.2-alpha1

This build will log any device names that cannot be decoded and hide them from the list instead of crashing.  Please try the build and share the log file so that we can see which audio devices were causing the problem.  Thanks!

**Comment by martjay** [comment]
> Thanks @martjay . I was not able to reproduce the problem in Windows 11 Chinese Simplified, but I think I understand what is happening. Please try this build: https://github.com/stargatedaw/stargate/releases/tag/release-24.02.2-alpha1
> 
> This build will log any device names that cannot be decoded and hide them from the list instead of crashing. Please try the build and share the log file so that we can see which audio devices were causing the problem. Thanks!

[stargate.log](https://github.com/stargatedaw/stargate/files/14035337/stargate.log)

**Comment by L3337** [comment]
Thanks @martjay .  This one should prevent all of the crashes:

https://github.com/stargatedaw/stargate/releases/tag/release-24.02.2-alpha2

**Comment by martjay** [comment]
> Thanks @martjay . This one should prevent all of the crashes:
> 
> https://github.com/stargatedaw/stargate/releases/tag/release-24.02.2-alpha2

It works now. Thank you. I hope in the future you can support VST plugins.

**Comment by L3337** [comment]
Glad it works, thanks again for reporting @martjay .  I am considering external plugin support for Stargate DAW v2, but there are no timeline planned to start that work yet.
