### ISSUE TITLE
Linux: Random popup window positions on Wayland

### ISSUE THREAD

**Issue by ghost** [stargatedaw/stargate#5]
This is a [feature of Wayland](https://wayland-devel.freedesktop.narkive.com/6XzmsY3c/random-window-position-with-desktop-shell).

I implemented the workaround for this, but at some point it stopped working in Qt5, but it still works in Qt6.  The only thing preventing me from migrating fully to PyQt6 is that most Linux distros are not packaging it yet.

As a workaround, you can run this command, and Stargate will automatically find it and do the right thing:
```
pip install PyQt6
```

**Comment by Conan-Kudo** [comment]
I've made an issue to add this to Fedora Linux since we've already got Qt6 packaged.

You can track it here: https://pagure.io/fedora-kde/SIG/issue/127

**Comment by ghost** [comment]
Nice, that will be a very welcome addition :-) 

I develop Stargate on Fedora + KDE

**Comment by L3337** [comment]
Eliminated by sheer brute force of consolidating everything into a single window that Wayland has no control over.

**Comment by Conan-Kudo** [comment]
PyQt6 is now in Fedora, for what it's worth. Sorry about not getting back to you about this.

**Comment by L3337** [comment]
Thanks @Conan-Kudo , no worries.
